#!/usr/bin/env Rscript

library(data.table)

# ============================================================
# 19_summarise_vep_annotation.R
#
# Purpose:
#   Summarise the local Ensembl VEP annotation output generated by:
#     scripts/18_run_vep_annotation.sh
#
# Input:
#   results/annotation/independent_lead_snps_vep_output.txt
#
# Outputs:
#   results/annotation/independent_lead_snps_vep_clean_summary.txt
#   results/annotation/vep_gene_summary.txt
#   results/annotation/vep_consequence_summary.txt
#
# Notes:
#   - The input is VEP tab output for all independent lead SNPs.
#   - VEP can return multiple rows per SNP because one variant may affect
#     several transcripts, genes, regulatory features, or consequences.
#   - The clean summary keeps one unique row per annotated feature/consequence.
# ============================================================

script_file <- sub("--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])
script_dir <- if (!is.na(script_file)) dirname(normalizePath(script_file)) else getwd()
project_dir <- dirname(script_dir)

annotation_dir <- file.path(project_dir, "results", "annotation")

vep_file <- file.path(annotation_dir, "independent_lead_snps_vep_output.txt")
clean_file <- file.path(annotation_dir, "independent_lead_snps_vep_clean_summary.txt")
gene_file <- file.path(annotation_dir, "vep_gene_summary.txt")
consequence_file <- file.path(annotation_dir, "vep_consequence_summary.txt")

stop_if_missing <- function(path, label) {
  if (!file.exists(path)) {
    stop(label, " not found: ", path, call. = FALSE)
  }
}

stop_if_missing(vep_file, "VEP annotation output")

message("Reading VEP output: ", vep_file)

# VEP tab output starts with metadata lines beginning with "##"; the actual
# header begins at "#Uploaded_variation". data.table::fread can skip directly
# to that header line.
vep <- fread(vep_file, skip = "#Uploaded_variation")

if (nrow(vep) == 0) {
  stop("VEP annotation output contains no data rows.", call. = FALSE)
}

# Remove the leading "#" from "#Uploaded_variation" so downstream column names
# are ordinary names.
names(vep) <- gsub("^#", "", names(vep))

wanted_cols <- c(
  "Uploaded_variation",
  "Location",
  "Allele",
  "Gene",
  "Feature",
  "Feature_type",
  "Consequence",
  "Existing_variation",
  "IMPACT",
  "SYMBOL",
  "BIOTYPE",
  "VARIANT_CLASS",
  "GENE_PHENO"
)

available_cols <- intersect(wanted_cols, names(vep))
missing_cols <- setdiff(wanted_cols, names(vep))

if (!"Uploaded_variation" %in% available_cols) {
  stop("VEP output is missing Uploaded_variation column.", call. = FALSE)
}

if (length(missing_cols) > 0) {
  message("Optional VEP column(s) not present: ", paste(missing_cols, collapse = ", "))
}

# Keep a compact table with the annotation fields needed for reporting.
clean <- unique(vep[, ..available_cols])
setnames(clean, "Uploaded_variation", "SNP")
setorder(clean, SNP, Gene, Feature, Consequence)

# Count how often each gene symbol appears across unique VEP annotation rows.
gene_summary <- clean[
  !is.na(SYMBOL) & SYMBOL != "-",
  .N,
  by = SYMBOL
][order(-N, SYMBOL)]

# Count the VEP consequence categories across unique annotation rows.
consequence_summary <- clean[
  !is.na(Consequence) & Consequence != "-",
  .N,
  by = Consequence
][order(-N, Consequence)]

fwrite(clean, clean_file, sep = "\t", quote = FALSE, na = "NA")
fwrite(gene_summary, gene_file, sep = "\t", quote = FALSE, na = "NA")
fwrite(consequence_summary, consequence_file, sep = "\t", quote = FALSE, na = "NA")

message("Written: ", clean_file)
message("Written: ", gene_file)
message("Written: ", consequence_file)
message("Rows in clean annotation table: ", nrow(clean))
message("Unique annotated SNPs: ", uniqueN(clean$SNP))
message("Unique annotated genes: ", nrow(gene_summary))
